# Generated by Django 5.0.1 on 2024-02-03 15:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(default='Expert Advice, Visa Guidance, and Success Stories', max_length=100)),
                ('business_name', models.CharField(default='Goreba Gateway', max_length=20)),
                ('company', models.CharField(default='Goreba', max_length=20)),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('short_description', models.CharField(blank=True, default='', max_length=50)),
                ('story_headline', models.CharField(blank=True, default='Goreba Gateway ~ Prologue', max_length=20)),
                ('business_story', ckeditor.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, default='+1 (514) 258 7260', max_length=20)),
                ('address', models.CharField(blank=True, default='153 Cresthaven Dr. Nepean, ON, K2G 6T2 Canada', max_length=50)),
                ('email', models.CharField(blank=True, default='goreba.gateway@gmail.com', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('MAINTENANCE', 'MAINTENANCE')], max_length=15)),
                ('icon', models.ImageField(blank=True, upload_to='images/goreba/')),
                ('business_logo', models.ImageField(blank=True, upload_to='images/goreba/')),
                ('business_banner', models.ImageField(blank=True, upload_to='images/goreba')),
                ('facebook_link', models.CharField(default='https://www.facebook.com/goreba.gateway', max_length=50)),
                ('instagram_link', models.CharField(default='https://www.instagram.com/goreba.gateway/', max_length=50)),
                ('twitter_link', models.CharField(default='https://twitter.com/goreba_canada', max_length=50)),
                ('youtube_link', models.CharField(default='https://www.youtube.com/@GorebaGateway', max_length=75)),
                ('linkedin_link', models.CharField(default='https://www.linkedin.com/company/goreba-gateway', max_length=50)),
                ('tiktok_link', models.CharField(default='https://tiktok.com/@goreba_gateway', max_length=50)),
                ('smtp_server', models.CharField(blank=True, max_length=50)),
                ('smtp_email', models.CharField(blank=True, max_length=50)),
                ('smtp_password', models.CharField(blank=True, max_length=10)),
                ('smtp_port', models.CharField(blank=True, max_length=5)),
                ('return_policy', ckeditor.fields.RichTextField(blank=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True)),
                ('cookie_policy', ckeditor.fields.RichTextField(blank=True)),
                ('announcements', ckeditor.fields.RichTextField(blank=True)),
                ('message_to_viewers', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
